package za.co.hpsc.web.models.image.response;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.http.MediaTypeFactory;
import za.co.hpsc.web.models.Response;
import za.co.hpsc.web.models.image.request.ImageRequest;
import za.co.hpsc.web.utils.ValueUtil;

import java.net.URLConnection;
import java.util.List;
import java.util.UUID;

/**
 * Represents a response object specifically designed for handling images.
 * This class extends the functionality of the {@link Response} superclass
 * by including additional fields and behaviours related to image-specific
 * properties, such as file path, file name, and MIME type.
 * <p>
 * The {@code ImageResponse} class provides multiple constructors for
 * creating instances with varying levels of details and integrates
 * MIME type detection based on file names when not explicitly provided.
 */
@NoArgsConstructor
public class ImageResponse extends Response {
    @Getter
    @Setter
    @NotNull
    private String filePath = "";
    @Getter
    @Setter
    @NotNull
    private String fileName = "";

    @Getter
    @NotNull
    private String mimeType = "";

    /**
     * Constructs a new {@code ImageResponse} object with specified UUID, title,
     * file path, file name, and MIME type.
     *
     * <p>
     * This constructor initialises the fields and ensures that the
     * file path and file name are not null by substituting empty strings for null values.
     * A randomly generated UUID is assigned through the superclass constructor
     * if the provided UUID is null.
     * The MIME type is set using the {@link #setMimeType} method.
     * </p>
     *
     * @param uuid     a unique identifier for the image response. If null,
     *                 a new UUID will be generated by the superclass constructor.
     * @param title    the title of the image.
     *                 Must not be null or blank.
     * @param filePath the file path where the image is stored.
     *                 If null, an empty string is assigned.
     * @param fileName the name of the file containing the image.
     *                 If null, an empty string is assigned.
     * @param mimeType the MIME type of the image.
     *                 If null or blank, it will be inferred from the file name.
     */
    public ImageResponse(UUID uuid, @NotNull @NotBlank String title, String filePath, String fileName,
                         String mimeType) {
        super(uuid, title);
        this.filePath = ValueUtil.nullAsEmptyString(filePath);
        this.fileName = ValueUtil.nullAsEmptyString(fileName);
        setMimeType(mimeType);
    }

    /**
     * Constructs a new {@code ImageResponse} object with the specified details.
     *
     * <p>
     * This constructor initialises the fields and ensures that the
     * file path and file name are not null by substituting empty strings for null values.
     * A randomly generated UUID is assigned through the superclass constructor
     * if the provided UUID is null.
     * The MIME type is set using the {@link #setMimeType} method.
     * </p>
     *
     * @param uuid        a unique identifier for the image response. If null,
     *                    a new UUID will be generated by the superclass constructor.
     * @param title       the title of the image.
     *                    Must not be null or blank.
     * @param summary     a brief summary of the image.
     *                    Can be null.
     * @param description a detailed description of the image.
     *                    Can be null.
     * @param category    the category under which the image is classified.
     *                    Can be null.
     * @param tags        a list of tags associated with the image.
     *                    If null, an empty list will be assigned.
     * @param filePath    the file path where the image is stored.
     *                    If null, an empty string is assigned.
     * @param fileName    the name of the file containing the image.
     *                    If null, an empty string is assigned.
     * @param mimeType    the MIME type of the image.
     *                    If null or blank, it will be inferred from the file name.
     */
    public ImageResponse(UUID uuid, @NotNull @NotBlank String title, String summary,
                         String description, String category, List<String> tags, String filePath,
                         String fileName, String mimeType) {
        super(uuid, title, summary, description, category, tags);
        this.filePath = ValueUtil.nullAsEmptyString(filePath);
        this.fileName = ValueUtil.nullAsEmptyString(fileName);
        setMimeType(mimeType);
    }

    /**
     * Constructs a new {@code ImageResponse} object with the specified details.
     *
     * <p>
     * This constructor initialises the fields and ensures that the
     * file path and file name are not null by substituting empty strings for null values.
     * A randomly generated UUID is assigned through the superclass constructor.
     * Additionally, the MIME type is automatically set using the {@link #setMimeType} method.
     * </p>
     *
     * @param title       the title of the image.
     *                    Must not be null or blank.
     * @param summary     a brief summary of the image.
     *                    Can be null.
     * @param description a detailed description of the image.
     *                    Can be null.
     * @param category    the category under which the image is classified.
     *                    Can be null.
     * @param tags        a list of tags associated with the image.
     *                    If null, an empty list will be assigned.
     * @param filePath    the file path where the image is stored.
     *                    If null, an empty string is assigned.
     * @param fileName    the name of the file containing the image.
     *                    If null, an empty string is assigned.
     */
    public ImageResponse(@NotNull @NotBlank String title, String summary, String description,
                         String category, List<String> tags, String filePath, String fileName) {
        super(null, title, summary, description, category, tags);
        this.filePath = ValueUtil.nullAsEmptyString(filePath);
        this.fileName = ValueUtil.nullAsEmptyString(fileName);
        setMimeType();
    }

    /**
     * Constructs a new {@code ImageResponse} object using the details from the provided
     * {@link ImageRequest}.
     *
     * <p>
     * This constructor initialises the {@code ImageResponse} fields based on the
     * information encapsulated in the given {@link ImageRequest}. The attributes such as
     * title, summary, description, category, tags, file path, and file name are copied
     * from the {@link ImageRequest} instance.
     * A randomly generated UUID is assigned through the superclass constructor.
     * </p>
     *
     * @param imageRequest the {@link ImageRequest} object containing the image metadata;
     *                     Must not be null.
     */
    public ImageResponse(@NotNull ImageRequest imageRequest) {
        // Initialises response fields from request attributes
        this(imageRequest.getTitle(), imageRequest.getSummary(), imageRequest.getDescription(),
                imageRequest.getCategory(), imageRequest.getTags(), imageRequest.getFilePath(),
                imageRequest.getFileName());
    }

    /**
     * Sets the MIME type for the current image response instance.
     * If the provided MIME type is null or blank, it attempts to determine the MIME type
     * based on the file name using {@link MediaTypeFactory}.
     *
     * @param mimeType the MIME type to be set; if null or blank, an attempt will be made
     *                 to infer it from the file name.
     */
    public void setMimeType(String mimeType) {
        if ((mimeType != null) && (!mimeType.isBlank())) {
            // Set the MIME type directly
            this.mimeType = mimeType;

        } else {
            if ((this.fileName != null) && (!this.fileName.isBlank())) {
                // Infer MIME type from the file name
                String fileNameMimeType = URLConnection.guessContentTypeFromName(this.fileName);
                if ((fileNameMimeType != null) && (!fileNameMimeType.isEmpty())) {
                    this.mimeType = fileNameMimeType;
                }
            }
        }

        if (this.mimeType == null) {
            this.mimeType = "";
        }
    }

    /**
     * Sets the MIME type for the current image response instance.
     * This method delegates to {@link #setMimeType(String)} with a null argument.
     * As a result, it attempts to determine the MIME type based on the file name
     * if no specific MIME type is provided.
     */
    public void setMimeType() {
        setMimeType(null);
    }
}
