# STANDARD
## Database
spring.datasource.url=jdbc:mysql://localhost:3306/hpsc_dev
# Show the generated SQL statements (Spring Boot 3 property)
spring.jpa.properties.hibernate.show_sql=true
# Format the SQL (Spring Boot 3 property)
spring.jpa.properties.hibernate.format_sql=true
# Enable trace level for JDBC binding to display parameter values (Spring Boot 3 property)
logging.level.org.hibernate.orm.jdbc.bind=trace
## Development
spring.devtools.add-properties=true
